spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Employee
    username: root
    password: root
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
  application:
    name: lk.naseeha.SpringBoot.model.Employ
server:
  port: 8080